/* Generated by           cobc 3.1-rc1.0 */
/* Generated from         studentwrite.cbl */
/* Generated at           Sep 24 2020 11:59:42 */
/* GnuCOBOL build date    Jul 04 2020 17:17:54 */
/* GnuCOBOL package date  Jul 01 2020 00:39:30 UTC */
/* Compile command        cobc -x -free -g studentwrite.cbl */

/* Program local variables for 'StudentWrite' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* File StudentRecords */
static cob_file		*h_STUDENTRECORDS = NULL;
static unsigned char	h_STUDENTRECORDS_status[4];

/* File TransRecords */
static cob_file		*h_TRANSRECORDS = NULL;
static unsigned char	h_TRANSRECORDS_status[4];

/* File NewStudentRecords */
static cob_file		*h_NEWSTUDENTRECORDS = NULL;
static unsigned char	h_NEWSTUDENTRECORDS_status[4];

/* Call pointers */
static cob_call_union	call_logger2;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_12[46] __attribute__((aligned));	/* StudentRecords Record */
static cob_u8_t	b_17[46] __attribute__((aligned));	/* TransRecords Record */
static cob_u8_t	b_19[46] __attribute__((aligned));	/* NewStudentRecords Record */
static cob_u8_t	b_20[70] __attribute__((aligned));	/* LOGLINE */
static cob_u8_t	b_21[7] __attribute__((aligned));	/* ACTION */
static cob_u8_t	b_22[54] __attribute__((aligned));	/* WS-CONCAT-LOG */

/* End of local data storage */


/* Fields */
static cob_field f_8	= {46, b_12, &a_1};	/* StudentRecord */
static cob_field f_12	= {46, b_12, &a_2};	/* StudentRecords Record */
static cob_field f_13	= {46, b_17, &a_1};	/* TransRecord */
static cob_field f_15	= {7, b_17, &a_2};	/* TransStudentID */
static cob_field f_17	= {46, b_17, &a_2};	/* TransRecords Record */
static cob_field f_18	= {46, b_19, &a_2};	/* NewStudentRecord */
static cob_field f_19	= {46, b_19, &a_2};	/* NewStudentRecords Record */
static cob_field f_20	= {70, b_20, &a_2};	/* LOGLINE */
static cob_field f_21	= {7, b_21, &a_2};	/* ACTION */
static cob_field f_22	= {54, b_22, &a_2};	/* WS-CONCAT-LOG */

/* End of fields */

