/* Generated by           cobc 3.1-rc1.0 */
/* Generated from         studentwrite.cbl */
/* Generated at           Sep 24 2020 11:59:42 */
/* GnuCOBOL build date    Jul 04 2020 17:17:54 */
/* GnuCOBOL package date  Jul 01 2020 00:39:30 UTC */
/* Compile command        cobc -x -free -g studentwrite.cbl */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"studentwrite.cbl"
#define  COB_PACKAGE_VERSION		"3.1-rc1"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 24 2020 11:59:42"
#define  COB_MODULE_DATE		20200924
#define  COB_MODULE_TIME		115942

/* Global variables */
#include "studentwrite.c.h"

/* Function prototypes */

static int		StudentWrite ();
static int		StudentWrite_ (const int);
static void		StudentWrite_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (StudentWrite ());
}

/* Functions */

/* PROGRAM-ID 'StudentWrite' */

/* ENTRY 'StudentWrite' */

static int
StudentWrite ()
{
  return StudentWrite_ (0);
}

static int
StudentWrite_ (const int entry)
{
  /* Program local variables */
  #include "studentwrite.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 77        : Entry     StudentWrite            : studentwrite.cbl */
  l_2:;

  /* Line: 78        : Paragraph BEGIN                   : studentwrite.cbl */

  /* Line: 84        : OPEN               : studentwrite.cbl */
  module->module_stmt = 0x00100054;
  cob_trace_stmt (st_1);
  cob_open (h_STUDENTRECORDS, 1, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_6;
    goto l_1;
    l_6:
    frame_ptr--;
  }

  /* Line: 85        : OPEN               : studentwrite.cbl */
  module->module_stmt = 0x00100055;
  cob_trace_stmt (st_1);
  cob_open (h_TRANSRECORDS, 1, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_7;
    goto l_1;
    l_7:
    frame_ptr--;
  }

  /* Line: 86        : OPEN               : studentwrite.cbl */
  module->module_stmt = 0x00100056;
  cob_trace_stmt (st_1);
  cob_open (h_NEWSTUDENTRECORDS, 2, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_8;
    goto l_1;
    l_8:
    frame_ptr--;
  }

  /* Line: 88        : READ               : studentwrite.cbl */
  module->module_stmt = 0x00100058;
  cob_trace_stmt (st_2);
  cob_read_next (h_STUDENTRECORDS, NULL, 1);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0501)
    {

      /* Line: 89        : SET                : studentwrite.cbl */
      module->module_stmt = 0x00100059;
      cob_trace_stmt (st_3);
      memset (b_12, 255, 46);
    }
    else
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_9;
      goto l_1;
      l_9:
      frame_ptr--;
    }
  }

  /* Line: 92        : READ               : studentwrite.cbl */
  module->module_stmt = 0x0010005C;
  cob_trace_stmt (st_2);
  cob_read_next (h_TRANSRECORDS, NULL, 1);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0501)
    {

      /* Line: 93        : SET                : studentwrite.cbl */
      module->module_stmt = 0x0010005D;
      cob_trace_stmt (st_3);
      memset (b_17, 255, 46);
    }
    else
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_10;
      goto l_1;
      l_10:
      frame_ptr--;
    }
  }

  /* Line: 96        : PERFORM            : studentwrite.cbl */
  module->module_stmt = 0x00100060;
  cob_trace_stmt (st_4);
  for (;;)
  {
    if ((((int)cob_cmp (&f_8, &cob_all_high) == 0) && 
        ((int)cob_cmp (&f_13, &cob_all_high) == 0)))
      break;

    /* Line: 97        : EVALUATE           : studentwrite.cbl */
    module->module_stmt = 0x00100061;
    cob_trace_stmt (st_5);

    /* Line: 98        : WHEN               : studentwrite.cbl */
    module->module_stmt = 0x00100062;
    cob_trace_stmt (st_6);

    if (((int)memcmp (b_12, b_17, 7) < 0))
    {

      /* Line: 99        : WRITE              : studentwrite.cbl */
      module->module_stmt = 0x00100063;
      cob_trace_stmt (st_7);
      memcpy (b_19, b_12, 46);
      cob_write (h_NEWSTUDENTRECORDS, &f_18, 2162689, NULL, 0);
      if (unlikely(cob_glob_ptr->cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_11;
        goto l_1;
        l_11:
        frame_ptr--;
      }

      /* Line: 100       : READ               : studentwrite.cbl */
      module->module_stmt = 0x00100064;
      cob_trace_stmt (st_2);
      cob_read_next (h_STUDENTRECORDS, NULL, 1);
      if (unlikely(cob_glob_ptr->cob_exception_code != 0))
      {
        if (cob_glob_ptr->cob_exception_code == 0x0501)
        {

          /* Line: 101       : SET                : studentwrite.cbl */
          module->module_stmt = 0x00100065;
          cob_trace_stmt (st_3);
          memset (b_12, 255, 46);
        }
        else
        {
          /* PERFORM Default Error Handler */
          frame_ptr++;
          if (unlikely(frame_ptr == frame_overflow))
          	cob_fatal_error (COB_FERROR_STACK);
          frame_ptr->perform_through = 1;
          frame_ptr->return_address_ptr = &&l_12;
          goto l_1;
          l_12:
          frame_ptr--;
        }
      }
      goto l_5;
    }

    /* Line: 104       : WHEN               : studentwrite.cbl */
    module->module_stmt = 0x00100068;
    cob_trace_stmt (st_6);

    if (((int)memcmp (b_12, b_17, 7) > 0))
    {

      /* Line: 105       : DISPLAY            : studentwrite.cbl */
      module->module_stmt = 0x00100069;
      cob_trace_stmt (st_8);
      cob_display (0, 1, 4, &c_1, &f_15, &c_2, &f_13);

      /* Line: 106       : WRITE              : studentwrite.cbl */
      module->module_stmt = 0x0010006A;
      cob_trace_stmt (st_7);
      memcpy (b_19, b_17, 46);
      cob_write (h_NEWSTUDENTRECORDS, &f_18, 2162689, NULL, 0);
      if (unlikely(cob_glob_ptr->cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_13;
        goto l_1;
        l_13:
        frame_ptr--;
      }

      /* Line: 109       : MOVE               : studentwrite.cbl */
      module->module_stmt = 0x0010006D;
      cob_trace_stmt (st_9);
      cob_move (&f_18, &f_20);

      /* Line: 110       : MOVE               : studentwrite.cbl */
      module->module_stmt = 0x0010006E;
      cob_trace_stmt (st_9);
      memcpy (b_21, "INSERT ", 7);

      /* Line: 111       : STRING             : studentwrite.cbl */
      module->module_stmt = 0x0010006F;
      cob_trace_stmt (st_10);
      cob_string_init (&f_22, NULL);
      cob_string_delimited (NULL);
      cob_string_append (&f_21);
      cob_string_append (&f_20);
      cob_string_finish ();

      /* Line: 115       : CALL               : studentwrite.cbl */
      module->module_stmt = 0x00100073;
      cob_trace_stmt (st_11);
      cob_procedure_params[0] = &f_22;
      cob_glob_ptr->cob_call_params = 1;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_logger2.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
      {
        call_logger2.funcvoid = cob_resolve_cobol ("logger2", 0, 1);
      }
      b_2 = ((int (*)(void *))call_logger2.funcint) (b_22);

      /* Line: 117       : READ               : studentwrite.cbl */
      module->module_stmt = 0x00100075;
      cob_trace_stmt (st_2);
      cob_read_next (h_TRANSRECORDS, NULL, 1);
      if (unlikely(cob_glob_ptr->cob_exception_code != 0))
      {
        if (cob_glob_ptr->cob_exception_code == 0x0501)
        {

          /* Line: 118       : SET                : studentwrite.cbl */
          module->module_stmt = 0x00100076;
          cob_trace_stmt (st_3);
          memset (b_17, 255, 46);
        }
        else
        {
          /* PERFORM Default Error Handler */
          frame_ptr++;
          if (unlikely(frame_ptr == frame_overflow))
          	cob_fatal_error (COB_FERROR_STACK);
          frame_ptr->perform_through = 1;
          frame_ptr->return_address_ptr = &&l_14;
          goto l_1;
          l_14:
          frame_ptr--;
        }
      }
      goto l_5;
    }

    /* Line: 121       : WHEN               : studentwrite.cbl */
    module->module_stmt = 0x00100079;
    cob_trace_stmt (st_6);

    if (((int)memcmp (b_12, b_17, 7) == 0))
    {

      /* Line: 122       : DISPLAY            : studentwrite.cbl */
      module->module_stmt = 0x0010007A;
      cob_trace_stmt (st_8);
      cob_display (0, 1, 4, &c_3, &f_15, &c_4, &f_13);

      /* Line: 123       : WRITE              : studentwrite.cbl */
      module->module_stmt = 0x0010007B;
      cob_trace_stmt (st_7);
      memcpy (b_19, b_17, 46);
      cob_write (h_NEWSTUDENTRECORDS, &f_18, 2162689, NULL, 0);
      if (unlikely(cob_glob_ptr->cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_15;
        goto l_1;
        l_15:
        frame_ptr--;
      }

      /* Line: 126       : MOVE               : studentwrite.cbl */
      module->module_stmt = 0x0010007E;
      cob_trace_stmt (st_9);
      cob_move (&f_18, &f_20);

      /* Line: 127       : MOVE               : studentwrite.cbl */
      module->module_stmt = 0x0010007F;
      cob_trace_stmt (st_9);
      memcpy (b_21, "UPDATE ", 7);

      /* Line: 128       : STRING             : studentwrite.cbl */
      module->module_stmt = 0x00100080;
      cob_trace_stmt (st_10);
      cob_string_init (&f_22, NULL);
      cob_string_delimited (NULL);
      cob_string_append (&f_21);
      cob_string_append (&f_20);
      cob_string_finish ();

      /* Line: 131       : DISPLAY            : studentwrite.cbl */
      module->module_stmt = 0x00100083;
      cob_trace_stmt (st_8);
      cob_display (0, 1, 2, &c_5, &f_22);

      /* Line: 132       : CALL               : studentwrite.cbl */
      module->module_stmt = 0x00100084;
      cob_trace_stmt (st_11);
      cob_procedure_params[0] = &f_22;
      cob_glob_ptr->cob_call_params = 1;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_logger2.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
      {
        call_logger2.funcvoid = cob_resolve_cobol ("logger2", 0, 1);
      }
      b_2 = ((int (*)(void *))call_logger2.funcint) (b_22);

      /* Line: 140       : READ               : studentwrite.cbl */
      module->module_stmt = 0x0010008C;
      cob_trace_stmt (st_2);
      cob_read_next (h_TRANSRECORDS, NULL, 1);
      if (unlikely(cob_glob_ptr->cob_exception_code != 0))
      {
        if (cob_glob_ptr->cob_exception_code == 0x0501)
        {

          /* Line: 141       : SET                : studentwrite.cbl */
          module->module_stmt = 0x0010008D;
          cob_trace_stmt (st_3);
          memset (b_17, 255, 46);
        }
        else
        {
          /* PERFORM Default Error Handler */
          frame_ptr++;
          if (unlikely(frame_ptr == frame_overflow))
          	cob_fatal_error (COB_FERROR_STACK);
          frame_ptr->perform_through = 1;
          frame_ptr->return_address_ptr = &&l_16;
          goto l_1;
          l_16:
          frame_ptr--;
        }
      }
      goto l_5;
    }

    /* End EVALUATE */
    l_5:;
  }

  /* Line: 153       : CLOSE              : studentwrite.cbl */
  module->module_stmt = 0x00100099;
  cob_trace_stmt (st_12);
  cob_close (h_STUDENTRECORDS, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_17;
    goto l_1;
    l_17:
    frame_ptr--;
  }

  /* Line: 154       : CLOSE              : studentwrite.cbl */
  module->module_stmt = 0x0010009A;
  cob_trace_stmt (st_12);
  cob_close (h_TRANSRECORDS, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_18;
    goto l_1;
    l_18:
    frame_ptr--;
  }

  /* Line: 155       : CLOSE              : studentwrite.cbl */
  module->module_stmt = 0x0010009B;
  cob_trace_stmt (st_12);
  cob_close (h_NEWSTUDENTRECORDS, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_19;
    goto l_1;
    l_19:
    frame_ptr--;
  }

  /* Line: 159       : STOP RUN           : studentwrite.cbl */
  module->module_stmt = 0x0010009F;
  cob_trace_stmt (st_13);
  cob_stop_run (b_2);

  module->module_stmt = 0x001000BE;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : studentwrite.cbl */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  StudentWrite_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  memset (b_20, 32, 70);
  memset (b_21, 32, 7);
  memset (b_22, 32, 54);

  /* File initialization for StudentRecords */
  cob_file_malloc (&h_STUDENTRECORDS, NULL, 0, 0);
  h_STUDENTRECORDS->select_name = (const char *)"StudentRecords";
  h_STUDENTRECORDS->file_status = h_STUDENTRECORDS_status;
  memset (h_STUDENTRECORDS_status, '0', 2);
  h_STUDENTRECORDS->assign = (cob_field *)&c_6;
  h_STUDENTRECORDS->record = &f_12;
  h_STUDENTRECORDS->variable_record = NULL;
  h_STUDENTRECORDS->record_min = 0;
  h_STUDENTRECORDS->record_max = 46;
  h_STUDENTRECORDS->nkeys = 0;
  h_STUDENTRECORDS->keys = NULL;
  h_STUDENTRECORDS->file = NULL;
  h_STUDENTRECORDS->fd = -1;
  h_STUDENTRECORDS->organization = 1;
  h_STUDENTRECORDS->access_mode = 1;
  h_STUDENTRECORDS->lock_mode = 0;
  h_STUDENTRECORDS->open_mode = 0;
  h_STUDENTRECORDS->flag_optional = 0;
  h_STUDENTRECORDS->flag_line_adv = 0;
  h_STUDENTRECORDS->flag_select_features = 0;

  /* File initialization for TransRecords */
  cob_file_malloc (&h_TRANSRECORDS, NULL, 0, 0);
  h_TRANSRECORDS->select_name = (const char *)"TransRecords";
  h_TRANSRECORDS->file_status = h_TRANSRECORDS_status;
  memset (h_TRANSRECORDS_status, '0', 2);
  h_TRANSRECORDS->assign = (cob_field *)&c_7;
  h_TRANSRECORDS->record = &f_17;
  h_TRANSRECORDS->variable_record = NULL;
  h_TRANSRECORDS->record_min = 0;
  h_TRANSRECORDS->record_max = 46;
  h_TRANSRECORDS->nkeys = 0;
  h_TRANSRECORDS->keys = NULL;
  h_TRANSRECORDS->file = NULL;
  h_TRANSRECORDS->fd = -1;
  h_TRANSRECORDS->organization = 1;
  h_TRANSRECORDS->access_mode = 1;
  h_TRANSRECORDS->lock_mode = 0;
  h_TRANSRECORDS->open_mode = 0;
  h_TRANSRECORDS->flag_optional = 0;
  h_TRANSRECORDS->flag_line_adv = 0;
  h_TRANSRECORDS->flag_select_features = 0;

  /* File initialization for NewStudentRecords */
  cob_file_malloc (&h_NEWSTUDENTRECORDS, NULL, 0, 0);
  h_NEWSTUDENTRECORDS->select_name = (const char *)"NewStudentRecords";
  h_NEWSTUDENTRECORDS->file_status = h_NEWSTUDENTRECORDS_status;
  memset (h_NEWSTUDENTRECORDS_status, '0', 2);
  h_NEWSTUDENTRECORDS->assign = (cob_field *)&c_8;
  h_NEWSTUDENTRECORDS->record = &f_19;
  h_NEWSTUDENTRECORDS->variable_record = NULL;
  h_NEWSTUDENTRECORDS->record_min = 0;
  h_NEWSTUDENTRECORDS->record_max = 46;
  h_NEWSTUDENTRECORDS->nkeys = 0;
  h_NEWSTUDENTRECORDS->keys = NULL;
  h_NEWSTUDENTRECORDS->file = NULL;
  h_NEWSTUDENTRECORDS->fd = -1;
  h_NEWSTUDENTRECORDS->organization = 1;
  h_NEWSTUDENTRECORDS->access_mode = 1;
  h_NEWSTUDENTRECORDS->lock_mode = 0;
  h_NEWSTUDENTRECORDS->open_mode = 0;
  h_NEWSTUDENTRECORDS->flag_optional = 0;
  h_NEWSTUDENTRECORDS->flag_line_adv = 0;
  h_NEWSTUDENTRECORDS->flag_select_features = 0;

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:

  return 0;

}

/* End PROGRAM-ID 'StudentWrite' */

/* Initialize module structure for StudentWrite */
static void StudentWrite_module_init (cob_module *module)
{
  module->module_name = "StudentWrite";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())StudentWrite;
  module->module_cancel.funcptr = (void *(*)())StudentWrite_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

