/* Generated by           cobc 3.1-rc1.0 */
/* Generated from         studentwrite.cbl */
/* Generated at           Sep 24 2020 11:59:42 */
/* GnuCOBOL build date    Jul 04 2020 17:17:54 */
/* GnuCOBOL package date  Jul 01 2020 00:39:30 UTC */
/* Compile command        cobc -x -free -g studentwrite.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x21,   0,   0, 0x1000, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1	= {9, (cob_u8_ptr)"Insert - ", &a_3};
static const cob_field c_2	= {18, (cob_u8_ptr)" new record:      ", &a_3};
static const cob_field c_3	= {9, (cob_u8_ptr)"Update - ", &a_3};
static const cob_field c_4	= {18, (cob_u8_ptr)" existing record: ", &a_3};
static const cob_field c_5	= {24, (cob_u8_ptr)"Data after concatenate: ", &a_3};
static const cob_field c_6	= {104, (cob_u8_ptr)"C:\\Users\\ag4488\\Documents\\Visual Studio 2019\\Projects\\cobol-nodejs-data-hooks\\cobol-os\\data\\students.dat", &a_3};
static const cob_field c_7	= {104, (cob_u8_ptr)"C:\\Users\\ag4488\\Documents\\Visual Studio 2019\\Projects\\cobol-nodejs-data-hooks\\cobol-os\\data\\transins.dat", &a_3};
static const cob_field c_8	= {105, (cob_u8_ptr)"C:\\Users\\ag4488\\Documents\\Visual Studio 2019\\Projects\\cobol-nodejs-data-hooks\\cobol-os\\data\\students1.dat", &a_3};

static cob_field cob_all_high	= {1, (cob_u8_ptr)"\xff", &cob_all_attr};


/* Strings */
static const char st_1[]	= "OPEN";
static const char st_2[]	= "READ";
static const char st_3[]	= "SET";
static const char st_4[]	= "PERFORM";
static const char st_5[]	= "EVALUATE";
static const char st_6[]	= "WHEN";
static const char st_7[]	= "WRITE";
static const char st_8[]	= "DISPLAY";
static const char st_9[]	= "MOVE";
static const char st_10[]	= "STRING";
static const char st_11[]	= "CALL";
static const char st_12[]	= "CLOSE";
static const char st_13[]	= "STOP RUN";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"studentwrite.cbl"};
